deployments:
  - name: development
    description: development
    on_push: true

  - name: staging
    description: staging
    on_push: true
    on_push_branch: staging

  - name: production
    description: production
